### ISSUE TITLE
Invalid Function Error [Emacs 26.1]

### ISSUE THREAD

**Issue by pekingduck** [tbanel/orgaggregate#1]
When I tried out the first example (the one counting colors), I got an error:

orgtbl-to-aggregated-table-do-sums: Invalid function: ((symbol-function (quote math-read-preprocess-string)) (function identity))

Then I noticed `orgtbl-to-aggregated-table-do-sums` begins with an `letf`, which doesn't exist in Emacs 26.1 (which I am using). It worked after I changed `letf` to `cl-letf`.

**Comment by tbanel** [comment]
Thanks for letting me know. And for the fix. I will update the package accordingly.
Regards

**Comment by tbanel** [comment]
Fixed. Wait a few hours for the change to propagate to the Melpa Emacs packages repository.
