### ISSUE TITLE
Preserve horizontal lines in the aggregated tables when using the special column "hline"

### ISSUE THREAD

**Issue by Nicryc** [tbanel/orgaggregate#11]
When using the hline special column, instead of creating an actual column hline with numbers, it would be great if the horizontal lines where conserved in the aggregated tables.

**Comment by tbanel** [comment]
Good suggestion!
I will look into that. It should be convenient, tested, and it should not break compatibility (too much).
It should also be compatible with a possible future sorting feature (because if we sort the output, hlines may be scrambled).

**Comment by tbanel** [comment]
This new feature is coming. As it is closely related to sorting, I first implemented sorting.

**Comment by tbanel** [comment]
Ok, implemented

In the simplest form, just add `:hline 1` without specifying an `hline` column. This will output the same hlines as in the input.

In a more advanced usage, hlines can be driven by any sorted column, or even multiple sorted columns. (To sort a column, add a sorting specifier like `;^n` or `;^A` to the column description in `:cols`).

This new feature is already committed in this GitHub, and will be available on https://melpa.org in a few hours.

I close this issue. Feel free to open a new one if something is wrong.
