### ISSUE TITLE
Retain all columns when filtering via `:cond`

### ISSUE THREAD

**Issue by wuqui** [tbanel/orgaggregate#12]
It's awesome that you allow for filtering: that's useful all the time and critically missing from org-tables. 

However, one thing that's a bit cumbersome about the current implementation is that one has to always specify all the columns that should be retained after filtering. For me, the default case should be that all columns are retained and only the rows are filtered. Yet, one gets an empty table when not using the `:cols` specification altogether. 

If it requires too much work to change this, one more convenient solution might be to allow for an argument like `:cols all`?

**Comment by tbanel** [comment]
That is quite a specific use-case. Just filtering, no aggregation. But why not?
`:cols all` may become problematic if it happens that the input table has a column named `all`. Maybe a missing `:cols` could trigger this behavior.
I'll look at that.

**Comment by wuqui** [comment]
Thanks for your quick reply and for looking into this!

Coming from SQL and pandas/dplyr queries, I'm used to (1) filtering and (2) grouping/aggregation being two separate things. In many cases, I just want to use (1) to retrieve a subset of rows based on a certain condition.

Triggering this behaviour by leaving out the `:cols` keyword seems like a pretty clean solution to this. I guess having a separate kind of block that isn't called `#+begin: aggregrate` but `#+begin: filter` would be another option. But both would be certainly good enough and really useful 🙂

**Comment by tbanel** [comment]
Ok, done.

When the `:hcol` parameter is missing, all columns are taken.

Be aware that OrgAggregate is still an aggregating machine. If there are two identical rows int the input, only one will appear in the ouput.

I close this issue. Feel free to open a new one in case something is wrong.

**Comment by wuqui** [comment]
Again, thanks so much for implementing this. This is really useful for me 🤓
