### ISSUE TITLE
unknown rx from literal

### ISSUE THREAD

**Issue by nilsleh** [tbanel/orgaggregate#13]
I installed orgtbl-aggregate and attempted to just run the very first example given in the documentation. However, it returns the Error: "unknown rx from literal"" and I cannot find anything that explains this error. I am running Emacs 26.3

**Comment by tbanel** [comment]
I am on the road. I will investigate this odd behaviour as soon as possible.
The rx library appeared in Emacs 21.1. So the bug you found does not look like an old rx version.

May you try this?
- insert that in the *scratch* buffer of your Emacs
  (rx (literal "abc"))
- execute it by typing Ctrl-J after the last closing parenthesis
- tell me the result (it should be "abc")

Thanks for your bug report

**Comment by nilsleh** [comment]
The output of trying what you suggested is the following:
```
Debugger entered--Lisp error: (error "Unknown rx form ‘literal’")
  signal(error ("Unknown rx form ‘literal’"))
  error("Unknown rx form `%s'" literal)
  rx-form((literal "abc"))
  rx-to-string((literal "abc") t)
  #f(compiled-function (&rest regexps) #<bytecode 0x1c7ae21>)((literal "abc"))
  macroexpand((rx (literal "abc")) nil)
  macroexp-macroexpand((rx (literal "abc")) nil)
  macroexp--expand-all((rx (literal "abc")))
  macroexpand-all((rx (literal "abc")))
  eval-sexp-add-defvars((rx (literal "abc")))
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)
```

**Comment by tbanel** [comment]
Thanks Nilsleh
Ok, then your version of rx does not have `literal`. After investigating, it seems the `literal` feature appeared around June 26, 2019. You Emacs 26.3 was released shortly after, on August 28, 2019, and does not yet contain `literate`.
I will prepare a patch to avoid `literate`.
Stay tuned

**Comment by tbanel** [comment]
I've just published a patch to avoid the new `literal` feature of the rx library.
This should fix the issue you experienced.
You can test it either by loading https://github.com/tbanel/orgaggregate/blob/master/orgtbl-aggregate.el or by installing the new Melpa package which will be available in a few hours.
I close the issue. Please feel free to re-open it if you still have the issue.

**Comment by nilsleh** [comment]
thanks for responding so quickly, I have loaded the new orgtbl-aggregate.el and tried the first example from your README but I am sorry to say that now when attempting to run it, I receive `rx 'not' syntax error: 39`. In the messages buffer, the message before this error is `Updating dynamic block 'aggregate' at line 64`

**Comment by tbanel** [comment]
Well, I guess I have to load an old version of the rx library and make sure everything works.
I will do that
I re-open the issue
Please stay tuned

**Comment by tbanel** [comment]
I confirm that I get the same error as you, `rx 'not' syntax error: 39`, using the rx version of January 1, 2016.
This is fixed. Now orgaggregate works with any rx library up to 5 years old.
Please tell me if there is still an issue.
