### ISSUE TITLE
Add rows after aggregation?

### ISSUE THREAD

**Issue by shankar2k** [tbanel/orgaggregate#15]
Would it be possible to add a parameter ":post" that would add rows, columns, and hlines to the table after aggregation? Here is how I envision it working: Given the table "original" in README.org, I would like to do something like the following:

```
#+BEGIN: aggregate :table "original" :cols "Day sum(Quantity)" :post "hline rows(1)" :formula "@>$2=vsum(@I..II)"
| Day       | sum(Quantity) |
|-----------+---------------|
| Monday    |            14 |
| Tuesday   |            45 |
| Wednesday |            54 |
| Thursday  |            83 |
| Friday    |            22 |
|-----------+---------------|
|           |           218 |
#+TBLFM: @>$2=vsum(@I..II)
#+END:
```

For this to work, the rows and columns must be added after aggregation but _before_ the table formulas are executed. In principle, I could manually add the rows, columns myself after aggregation, but they would be removed whenever the table is reaggregated.

**Comment by tbanel** [comment]
Hi shankar2k

### Legitimate request
I found the need of some kind of post-processing too. I need to add a first row (right now I add it by hand). You need to add `hlines` and rows at the end.

There can be other needs. Maybe exchanging two rows, or deleting the fourth. How can we specify that in a `:post` parameter?

### Reinventing the wheel?
I feel difficult if not impossible to foresee every possible future need. I don't want to design a new small language just for post-processing. It would grow out of control each time someone express a new need. It would be difficult to document, to explain, to remember, to use, and to implement.

So, maybe this post-processing could leverage an existing language.

### 1st suggestion
A Lisp function or `lambda` that would receive the aggregated table as a Lisp list. It would be free to process this list in any way, as long as it returns a valid list.

Your example could be implemented like that:
```
(lambda (result)
  (append result '(hline ("" ""))))
```

### 2nd suggestion
A Lisp function or `lambda` that would operate on the already printed table.

Your example could be implemented like that:
```
(lambda ()
  (org-narrow-to-element)
  (goto-char (point-max))
  (forward-line -2)
  (org-table-insert-hline)
  (org-table-insert-row)
  (widen))
```
Note: an Emacs macro may qualify as a post-processing function, as a macro can be turned into a Lisp function.

Any thought or other suggestion?

**Comment by shankar2k** [comment]
Hi tbanel,

 I completely agree with you that a bespoke post-processing language would be infeasible to design and implement. I believe that `:post` should take a function or `lambda` as argument, as you recommend. 

Of your two suggestions, my selfish preference is for the first one, because for my use case, the `lambda` operating on the table as list is much more concise and "elegant" than the `lambda` that operates on the printed table. That said, I think the first suggestions also requires a shorter `lambda` for your use case and probably other peoples' use cases as well.  Also the second suggestion seems too low-level for users that aren't comfortable with elisp.

An alternate way to implement my use case would be to allow for multiple `:cols` parameters whose results would be concatenated together into one table. But that wouldn't be able to add a first row like you needs and probably would introduce other problems.

Thanks for looking into this!

**Comment by tbanel** [comment]
Good!
I will investigate the first suggestion.

    (lambda (result)
      (append result '(hline ("" ""))))

I did not understood the multiple ```:cols``` parameters. In your example, do you mean that 2 ```:cols``` would generate the 2 following tables:

    | Day       | sum(Quantity) |
    |-----------+---------------|
    | Monday    |            14 |
    | Tuesday   |            45 |
    | Wednesday |            54 |
    | Thursday  |            83 |
    | Friday    |            22 |

and

    |-----------+---------------|
    |           |           218 |

with ```218``` being another aggregation?

**Comment by tbanel** [comment]
Done

The ```:post``` parameter may be
- a ```lambda```
- the name of a Lisp function
- a reference to a Babel block

This is explained in the _README_, chapter _Post processing_

**Comment by shankar2k** [comment]
I just tested the new :post parameter out and it worked great for me. Thanks so much!

**Comment by shankar2k** [comment]
> I did not understood the multiple `:cols` parameters. In your example, do you mean that 2 `:cols` would generate the 2 following tables:
> 
> ```
> | Day       | sum(Quantity) |
> |-----------+---------------|
> | Monday    |            14 |
> | Tuesday   |            45 |
> | Wednesday |            54 |
> | Thursday  |            83 |
> | Friday    |            22 |
> ```
> 
> and
> 
> ```
> |-----------+---------------|
> |           |           218 |
> ```
> 
> with `218` being another aggregation?

That's right. My motivation for the :post functionality is that I would like to replicate the behavior of an Excel pivot table I used to balance my expenses:

![Screenshot 2022-09-26 110506](https://user-images.githubusercontent.com/1454572/192242632-5041c91a-5d99-4a3f-99cf-b89ecae5510f.png)

I see now that what I envisioned would be complicated to implement. The second aggregation has only one column, so there would need to be additional syntax to specify that second result should line up with the second column of the first aggregation. 

That said, I imagine there are many scenarios where one would want to perform an aggregation broken down with respect to a column, but also see the "total" aggregation over all data. I'll let you know if I think of a simpler way to specify this behavior.

**Comment by tbanel** [comment]
> I just tested the new :post parameter out and it worked great for me. Thanks so much!

You are welcome!

**Comment by tbanel** [comment]
> That's right. My motivation for the :post functionality is that I would like to replicate the behavior of an Excel pivot table I used to balance my expenses:
> 
> ![Screenshot 2022-09-26 110506](https://user-images.githubusercontent.com/1454572/192242632-5041c91a-5d99-4a3f-99cf-b89ecae5510f.png)
> 
> I see now that what I envisioned would be complicated to implement. The second aggregation has only one column, so there would need to be additional syntax to specify that second result should line up with the second column of the first aggregation.
> 
> That said, I imagine there are many scenarios where one would want to perform an aggregation broken down with respect to a column, but also see the "total" aggregation over all data. I'll let you know if I think of a simpler way to specify this behavior.

Yes, complicated to implement. And **to specify**.

### Excel design flaw

I have always thought that the Excel design was flawed from the first day (1984 on Apple McIntosh). A single gigantic 32000x32000 cells spreadsheet feels like a total freedom. But it is the opposite: a hard constraint.

I've seen through the years so many people trying to fit several in-homogeneous tables in this big space. Over and over they had the same problem: 2 or more tables share the same columns or rows. Want to make a cell taller? It gets taller in the neighbour table too.

There is another problem that comes over and over. A table have carefully crafted formulas. Then a row needs to be added at the end. Often, the row gets added _"outside"_ the table (it is not taken into account by the formulas). So people tend to add the row before the last row. This is because there is no such thing as _"a well delimited table"_.

### One table, one purpose

A cleaner design would be: _**"one table, one purpose"**_.

Granted, we often want a table with a grand-total at the end. This is a legitimate requirement. But it is no longer a table. It is a more sophisticated object.

Moreover, if we want the grand-total, but also the standard deviation and the maximum, in which cells should we put those 3 numbers?

    | Day       | Amount |
    |-----------+--------+
    | Monday    |     14 |
    | Tuesday   |     45 |
    | Wednesday |     54 |
    | Thursday  |     83 |
    | Friday    |     22 |
    |-----------+--------+----|
    | 27.409852 |    218 | 83 |

If we insist in making the last row special, then we no longer have clean formulas or algorithms that span all the rows of table. We have to add algorithmic logic to process the last row in a special way.

### More sophistication

So I would say that if we want an aggregation by days, another by colors, and a grand-total, and we follow the _"one table, one purpose"_ principle, then we end up with 3 tables. And that is good.

Or we may use more sophisticated objects. And we need a more sophisticated tool than ```orgtb-aggregate```.

**Comment by shankar2k** [comment]
I agree both with the design principle **"_one table, one purpose_"** and that a table with "grand total"-type statistics at the end is a legitimate and commonly needed requirement. But while I agree that including a special grand-total row would indeed complicate the formulas and algorithms, I don't believe that a table with a grand total  necessarily violates the "_one table, one purpose_" principle.

In your example above, of the three statistics, only `sum` is actually a grand total. The other two, `std` and `max` are statistics calculated not on the original data (in table "original" from the README), but on the aggregated results in your example. Given that these two statistics are aggregations of aggregations, it makes perfect sense to me that they should be in a second derived table. 

The "Amount" column and its grand total have related algorithms. The Amount column is computing from the table "original" for each day `d` in column `Day`, `sum(Quantity | Day=d)`, where the notation `|` means "conditioned on". The grand total is simply `sum(Quantity)`, that is, conditioned on nothing. In all of your aggregation table examples in the README, every column contains either a variable upon which to condition aggregations (e.g. `Day`, `Color`), or a statistic that aggregates the data in a column conditioned on those variables. It believe it should be feasible to specify as a modifier to a formula that there should be a "grand accumulation" at the end.

Here is an example to illustrate how I envision it working:

```
#+BEGIN: aggregate :table original :cols "Day vmean(Level);G vsum(Quantity);G"
| Day       | vmean(Level) | vsum(Quantity) |
|-----------+--------------+----------------|
| Monday    |         27.5 |             14 |
| Tuesday   |           43 |             45 |
| Wednesday |           18 |             54 |
| Thursday  |           43 |             83 |
| Friday    |            8 |             22 |
|-----------+--------------+----------------|
|           |    27.928571 |            218 |
#+END
```
Here, the modifier ;G indicates that each formula should have a "grand accumulation" at the end.

These grand accumulations could in principle be computed in a second accumulation table as you say. But this is a bit unsatisfying to me, because the second table results wouldn't line up with the first table results, both because the second table has one fewer column and its two columns are not padded to the same length as the corresponding columns in the first table.

I believe this feature would be useful to many people, and would enable aggregation tables that achieve grand accumulation with much shorter and cleaner syntax than my current approach using `:post`.

**Comment by shankar2k** [comment]
> > I just tested the new :post parameter out and it worked great for me. Thanks so much!
> 
> You are welcome!

Thanks for listing me as a contributor to your package! Instead of my github username, could you put my real name (Shankar Rao) there?

**Comment by tbanel** [comment]
Good points! Especially _"these two statistics are aggregations of aggregations"_.

And of course, seeing the total of a column is often useful. No problem with that.

My point is that adding a last line to the table, makes this table final. It can no longer be the input of further processing.

In SQL, for instance, nobody adds a total at the end of a table. The total always comes from some sort of
```select sum(C) from TABLE```.

**Comment by tbanel** [comment]
Your name, Shankar Rao, is now listed in the README
Thanks for your contribution!
