### ISSUE TITLE
Add support for new added Org Mode dynamic block inserting API

### ISSUE THREAD

**Issue by stardiviner** [tbanel/orgaggregate#2]
Here is my new submitted API code: https://code.orgmode.org/bzg/org-mode/commit/34b71a0ca97559d9195c0f938c19ec292e4e77ec

I'm inspired by your package API code.

And here is the discusssion in mailing list:

- https://lists.gnu.org/archive/html/emacs-orgmode/2018-11/msg00183.html
- https://lists.gnu.org/archive/html/emacs-orgmode/2018-12/msg00026.html
- https://lists.gnu.org/archive/html/emacs-orgmode/2019-01/msg00016.html

There might be missing in the list. Because they are not all in same searched thread result.

**Comment by stardiviner** [comment]
Here is my temporary added code:
```elisp
;;; add `orgtbl-aggregate' dynamic blocks into list.
(org-dynamic-block-define "columnview" 'org-insert-columns-dblock)
(org-dynamic-block-define "aggregate" 'org-insert-dblock:aggregate)
(org-dynamic-block-define "invoice" 'org-insert-dblock:invoice)
(org-dynamic-block-define "join" 'org-insert-dblock:join)
(org-dynamic-block-define "org-gantt" 'org-insert-dblock:org-gantt)
(org-dynamic-block-define "propview" 'org-insert-dblock:propview)
(org-dynamic-block-define "transpose" 'org-insert-dblock:transpose)
```

**Comment by tbanel** [comment]
Done! Added
```
(if (fboundp 'org-dynamic-block-define)
    (org-dynamic-block-define "aggregate" 'org-insert-dblock:aggregate))
```
The `fboundp` test ensures that this setting does not crash on older releases of Org Mode.
