### ISSUE TITLE
Referene name of aggrgated table is missing

### ISSUE THREAD

**Issue by DirkSchmitt** [tbanel/orgaggregate#3]
I want to use an aggregated table as data source for **gnuplot**.
For this I have to know the (not yet documented) table name or assign a new table name.

I tried to add `#+TBLNAME: myTable` but after recalculation it is removed.
I suggest to retain this annotation in a similar way as e.g. `#+TBLFM: …`

**Comment by tbanel** [comment]
Hi Dirk
Good suggestion!
I will look how to do that.
Regards
Thierry

**Comment by tbanel** [comment]
Done
Thanks Dirk for reporting this issue

**Comment by DirkSchmitt** [comment]
Thanks for the quick implementation.
There is a minor issue that the `#+TBLNAMÈ` annotation indentation on each recalculation is increasing.

**Comment by tbanel** [comment]
I guess the issue happens when the `#+BEGIN` line is indented?
If so, the issue is fixed.
Please let me know if not.
Note that this same issue is now fixed in the `orgtb-join` sister package too.
Thanks for reporting!

**Comment by DirkSchmitt** [comment]
Thanks. The alignment is now correct.
