### ISSUE TITLE
Underscore in Header Line breaks vsum

### ISSUE THREAD

**Issue by falloutphil** [tbanel/orgaggregate#6]
Hi,

Nice package - thanks for sharing it!

I've found that whilst the following fails:
```#+BEGIN: aggregate :table "covid" :cols "Country vsum(Cumulative_cases)"```

If I rename the column, removing the underscore it works:
```#+BEGIN: aggregate :table "covid" :cols "Country vsum(Cumulative)"```

Can this be fixed in the code?

**Comment by falloutphil** [comment]
My bad.  Name needs to be wrapped in single quotes if it contains an underscore.

I'll close this.

**Comment by tbanel** [comment]
Hi @falloutphil
Yes, single or double quotes are a way to mention columns with weird characters in their names (spaces, +, -, & etc.). Actually, underscore is not such a weird character. I will look at how to handle it as a regular character.
Thanks for your feedback!
