### ISSUE TITLE
How calculate values of column#x in whole rows contain some text?

### ISSUE THREAD

**Issue by alexei-28** [tbanel/orgaggregate#7]
Emacs 26.1

Suppose I has org table:

| Task           | State       | Duration|
|----------------+------------+------------|
| RP-135      | Taken     |      5.50  |
| RP-77        | Taken     |       1.50 |
| RP-135      | Taken     |       4.50 |
| RP-135      | Taken     |       1.50 |
| RP-77        | Taken     |       1.50 |
| RP-162      | Taken     |       6.00 |

I need to sum all values in column **Duration** in whole rows that in column "Task" contain **RP-77** ?

The result must be **3.00**

**Comment by tbanel** [comment]
First give a name to your table, for instance "mytable"

Then ask Aggregate to sum up the "Duration" column while grouping with
values found in the "Task" column.

#+name: mytable
| Task   | State | Duration |
|--------+-------+----------|
| RP-135 | Taken |     5.50 |
| RP-77  | Taken |     1.50 |
| RP-135 | Taken |     4.50 |
| RP-135 | Taken |     1.50 |
| RP-77  | Taken |     1.50 |
| RP-162 | Taken |     6.00 |

#+BEGIN: aggregate :table "mytable" :cols "Task vsum(Duration);f2"
| Task   | vsum(Duration);f2 |
|--------+-------------------|
| RP-135 |             11.50 |
| RP-77  |              3.00 |
| RP-162 |              6.00 |
#+END:

We get 3.00 as expected for rows containing RP-77

If you are interested only in RP-77, you can filter and keep only rows
that contain "RP-77":

#+BEGIN: aggregate :table "mytable" :cols "vsum(Duration);f2" :cond
(string= Task "RP-77")
| vsum(Duration);f2 |
|-------------------|
|              3.00 |
#+END:

I hope this answer you question
Regards


Le 06/09/2020 à 20:55, a_subscriber a écrit :

**Comment by tbanel** [comment]
First give a name to your table, for instance `mytable`

Then ask Aggregate to sum up the `Duration` column while grouping with values found in the `Task` column.

    #+name: mytable
    | Task   | State | Duration |
    |--------+-------+----------|
    | RP-135 | Taken |     5.50 |
    | RP-77  | Taken |     1.50 |
    | RP-135 | Taken |     4.50 |
    | RP-135 | Taken |     1.50 |
    | RP-77  | Taken |     1.50 |
    | RP-162 | Taken |     6.00 |

    #+BEGIN: aggregate :table "mytable" :cols "Task vsum(Duration);f2"
    | Task   | vsum(Duration);f2 |
    |--------+-------------------|
    | RP-135 |             11.50 |
    | RP-77  |              3.00 |
    | RP-162 |              6.00 |
    #+END:

We get `3.00` as expected for rows containing `RP-77`

If you are interested only in `RP-77`, you can filter and keep only rows that contain `RP-77`:

    #+BEGIN: aggregate :table "mytable" :cols "vsum(Duration);f2" :cond (string= Task "RP-77")
    | vsum(Duration);f2 |
    |-------------------|
    |              3.00 |
    #+END:

I hope this answer you question
Regards
